//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Quero.rc
//
#define IDS_PROJNAME                    100
#define IDR_QUEROBAND                   101
#define IDM_QUERO                       102
#define IDM_LOGO                        103
#define IDC_COMBOENGINE                 104
#define IDC_EDITBOX                     105
#define IDC_COMBOQUERO                  106
#define IDS_QUEROFILTER_DESC            108
#define IDR_QUEROFILTER                 109
#define IDS_PROMPT                      110
#define IDS_EMPTY                       111
#define IDS_POPUPBLOCKED                112
#define IDS_CONTENTBLOCKED              113
#define IDS_HIGHLIGHTING                114
#define IDS_ON                          115
#define IDS_OFF                         116
#define IDS_LUCKYSEARCH                 117
#define IDS_FIND_FINISHED               118
#define IDS_FIND_NOTFOUND               119
#define IDS_CTXMENU_HIGHLIGHT           120
#define IDM_BACK                        120
#define IDS_CTXMENU_GOTOURL             121
#define IDM_FORWARD                     121
#define IDS_BLOCKED_MENU_1DIV           122
#define IDM_REFRESH                     122
#define IDS_BLOCKED_MENU_NDIVS          123
#define IDM_STOP                        123
#define IDS_BLOCKED_MENU_1ADSCRIPT      124
#define IDM_HOME                        124
#define IDS_BLOCKED_MENU_NADSCRIPTS     125
#define IDS_BLOCKED_MENU_BLOCK_ADS      126
#define IDS_BLOCKED_MENU_BLOCK_POPUPS   127
#define IDS_BLOCKED_MENU_ALLOWED_SITES  128
#define IDS_HISTORY                     129
#define IDS_PASTE_AND_GO                130
#define IDS_BLOCKED_MENU_TEMP_UNBLOCK   131
#define IDS_UP_ONE_LEVEL                132
#define IDI_QUERO                       140
#define IDI_QUERO_WHITE                 141
#define IDS_HINT_FIND                   150
#define IDS_HINT_QUERO_ALT_Q            151
#define IDS_HINT_QUERO_ALT_SHIFT_Q      152
#define IDS_HINT_GOTOURL                153
#define IDS_HINT_GOTOENGINE             154
#define IDS_HINT_QUERY                  155
#define IDS_HINT_BACK                   156
#define IDS_HINT_BACK_TO                157
#define IDS_HINT_FORWARD                158
#define IDS_HINT_FORWARD_TO             159
#define IDS_HINT_REFRESH                160
#define IDS_HINT_STOP                   161
#define IDS_HINT_HOME                   162
#define IDS_HINT_IDN                    163
#define IDS_HINT_123                    164
#define IDS_HINT_LOCK                   165
#define IDS_HINT_CONTENTBLOCKED         166
#define IDS_BLOCKED_MENU_HIDE_FLASH     167
#define IDS_HELP_FINDONPAGE             200
#define IDS_HELP_SELECTPROFILE          201
#define IDS_HELP_SELECTDEFAULT          202
#define IDI_BUTTON_GO                   202
#define IDS_HELP_APPEARANCE             203
#define IDS_HELP_RESIZE                 204
#define IDS_HELP_HIGHLIGHT              205
#define IDI_BUTTON_GO_HOT               205
#define IDC_CHKBLOCKPOPUPS              205
#define IDS_HELP_BLOCKADS               206
#define IDC_CHKBLOCKFLASH               206
#define IDS_HELP_HIDEFLASHADS           207
#define IDS_HELP_BLOCKPOPUPS            208
#define IDS_HELP_CLEARHISTORY           209
#define IDS_HELP_ABOUT                  210
#define IDS_HELP_ZOOM                   211
#define IDS_HELP_OPTIONS                212
#define IDC_CMDRESETWL                  214
#define IDI_SEARCH                      215
#define IDI_URL                         216
#define IDC_CHKSHOWFIRSTURL             219
#define IDI_ENGINE1                     222
#define IDI_BOOK                        223
#define IDI_CHART                       224
#define IDI_MAP                         225
#define IDI_MOVIE                       226
#define IDI_PRICE                       227
#define IDI_TELEPHONE                   228
#define IDI_TRAIN                       229
#define IDI_TROLLEY                     230
#define IDI_TV                          231
#define IDI_WEATHER                     232
#define IDI_SCIENCE                     234
#define IDI_IDN                         238
#define IDB_SHIELD                      242
#define IDI_OPT_NAVIGATION              245
#define IDI_OPT_ADBLOCKER               248
#define IDI_OPT_SEARCH                  249
#define IDS_OPTIONS_TITLE               250
#define IDS_OPTION_STANDARD             251
#define IDS_OPTION_MEDIUM               252
#define IDI_123                         252
#define IDS_OPTION_LARGE                253
#define IDI_COMPASS                     253
#define IDS_OPTION_GREENBLUE            254
#define IDI_LOCK                        254
#define IDS_OPTION_BLACK                255
#define IDI_OPT_SECURITY                255
#define IDS_OPTION_CTRL_Q               256
#define IDS_OPTION_ALT_Q                257
#define IDS_OPTION_ALT_D                258
#define IDS_OPTION_ALT_S                259
#define IDI_NAV_BACK                    259
#define IDS_OPTION_OPEN_SAMEWINDOW      260
#define IDI_NAV_FORWARD                 260
#define IDS_OPTION_OPEN_NEWWINDOW       261
#define IDI_NAV_STOP                    261
#define IDS_OPTION_OPEN_NEWTAB          262
#define IDI_NAV_REFRESH                 262
#define IDS_OPTION_OPEN_BACKGROUNDTAB   263
#define IDI_BIN                         263
#define IDS_PROFILES_DEFAULT            264
#define IDS_EDIT_SEARCH_PROFILE         265
#define IDS_EDIT_SEARCH_ENGINE          266
#define IDS_CODEPAGE_UTF8               267
#define IDC_ICON_OPT_NAVIGATION         267
#define IDS_CODEPAGE_Arabic             268
#define IDC_ICON_OPT_SEARCH             268
#define IDS_CODEPAGE_Baltic             269
#define IDC_ICON_OPT_ADBLOCKER          269
#define IDS_CODEPAGE_Central_European   270
#define IDI_NAV_BACK_DISABLED           270
#define IDC_ICON_OPT_SECURITY           270
#define IDS_CODEPAGE_Chinese_Simplified_GB2312 271
#define IDI_NAV_FORWARD_DISABLED        271
#define IDS_CODEPAGE_Chinese_Traditional_BIG5 272
#define IDI_SEARCH_NOTFOUND             272
#define IDC_ICON_OPT_BUTTONS            272
#define IDS_CODEPAGE_Cyrillic           273
#define IDI_OPT_BUTTONS                 273
#define IDS_CODEPAGE_Greek              274
#define IDI_NAV_BACK_HOT                274
#define IDS_CODEPAGE_Hebrew             275
#define IDI_NAV_FORWARD_HOT             275
#define IDS_CODEPAGE_Japanese           276
#define IDI_NAV_REFRESH_HOT             276
#define IDS_CODEPAGE_Korean             277
#define IDI_NAV_STOP_HOT                277
#define IDS_CODEPAGE_Thai               278
#define IDI_OPT_TYPEFIND                278
#define IDS_CODEPAGE_Turkish            279
#define IDI_NAV_HOME                    279
#define IDS_CODEPAGE_Vietnamese         280
#define IDI_NAV_HOME_HOT                280
#define IDS_CODEPAGE_Western_European   281
#define IDS_OPTION_PINK                 282
#define IDC_ICON_OPT_TYPEFIND           285
#define IDS_WL_ALLOW                    300
#define IDS_WL_DEFAULT                  301
#define IDS_WL_SITE                     302
#define IDS_WL_FLASH                    303
#define IDS_WL_BANNER                   304
#define IDS_WL_ADSCRIPT                 305
#define IDS_WL_DIV                      307
#define IDS_WL_IFRAME                   308
#define IDS_WL_POPUPS                   309
#define IDS_WL_IDN                      310
#define IDS_WL_GLYPHS                   311
#define IDS_WL_CONFIRM_RESET            312
#define IDS_WARN_IDN_TITLE              350
#define IDS_WARN_IDN_DESC               351
#define IDS_WARN_ILLEGAL_URL_TITLE      352
#define IDS_WARN_ILLEGAL_URL_DESC       353
#define IDS_WARN_MISSGLYPHS_TITLE       354
#define IDS_WARN_MISSGLYPHS_DESC        355
#define IDS_WARN_ASCIIRULES_VIOLATION_TITLE 356
#define IDS_WARN_ASCIIRULES_VIOLATION_DESC 357
#define IDS_ERR_QUERYTOOLONG            400
#define IDS_ERR_PUBLOCKER_UNAVAILABLE   401
#define IDS_ERR_WL_OVERFLOW             402
#define IDS_ERR_WL_PATTERNINVALID       403
#define IDS_ERR_WL_PATTERNNOTFOUND      404
#define IDS_ERR_PROFILES_OVERFLOW       405
#define IDS_ERR_SE_OVERFLOW             406
#define IDS_ERR_REQUIRED_FIELDS         407
#define IDS_ERR_OPERATION_LOCKED        408
#define IDS_TIP_QUERO_SHORTCUT          500
#define IDS_QUEROTHEME_FORMAT           1000
#define IDS_QUEROTHEME_VERSION          1001
#define IDS_QUEROTHEME_AUTHOR           1002
#define IDS_QUEROTHEME_NAME             1003
#define IDS_QUEROTHEME_NAVBUTTONSIZE    1004
#define IDS_QUEROTHEME_BUTTONSIZE       1005
#define IDS_QUEROTHEME_PADDINGY         1006
#define IDS_QUEROTHEME_COLORS           1100
#define ID_QUERO_DEFAULTENGINE          31000
#define ID_QUERO_FINDWORD               32000
#define ID_QUERO_SHOWURL                32774
#define ID_QUERO_FINDNEXT               32776
#define ID_QUERO_FONTSIZE_STANDARD      32781
#define ID_QUERO_FONTSIZE_MEDIUM        32782
#define ID_QUERO_FONTSIZE_LARGE         32783
#define ID_QUERO_FONTCOLOR_GREENBLUE    32799
#define ID_QUERO_FONTCOLOR_BLACK        32800
#define ID_QUERO_PROFILES               33000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        286
#define _APS_NEXT_COMMAND_VALUE         32824
#define _APS_NEXT_CONTROL_VALUE         322
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
